# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f2f30b88d8b8d78f5ef6f688a9b0cc8fbc7b5fc21bac759361533caeb9b7f31e9dfab7af806e0b601869cf1cfbd28012f7d477e920b4990a7fa9fdb88f0dfd4

test:
  secret_key_base: 7a7dfb215dd27b835609f30ec832cfa2e7e945920d0b88c20c4686d2bd9df54617104046148c1dddbe0b10ba45bb0694c627882c2ac533fc9e7e06d0349e6a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
